### ISSUE TITLE
Multiple errors on Emotion-Recognition.py

### ISSUE THREAD

**Issue by mathildebuenerd** [danz1ka19/Music-Emotion-Recognition#1]
Hi! I'm trying to use your script for analyzing few sounds. The `Feature-Extraction.py` file was working well but I keep getting errors on the `Emotion-Recognition.py`. I first had this one:

`KeyError: 'the label [class] is not in the [columns]'` 

I was thinking it's because there is no "class" column in the Emotion_features.csv file, so I have added it manually. But then I get a `ValueError: Found input variables with inconsistent numbers of samples: [35, 0]` error on line 34.

**Comment by ELDHOSE-P-A** [comment]
I faced the same issue. The column class and label are missing in the data generated by the Feature-Extractor.py file.  I think that these columns must be added by a function that is not the feature extractor.

**Comment by mathildebuenerd** [comment]
I cant remember if I finally managed to make it work...
But I created a classifier with tensorflow.js. It is based on the dataset provided in this repo, and the generated Emotion_features.json. It's not very accurate but you can give a try, I added instructions and an interface today, let me know if it's working.
You can try it there: https://github.com/mathildebuenerd/music-emotion-classifier
