### ISSUE TITLE
lack of label and class in Feature-Extraction.py 

### ISSUE THREAD

**Issue by Ealireza** [danz1ka19/Music-Emotion-Recognition#2]
i don't know why there is no label or class in Feature-Extraction.py 
and also i don't know how add it
please if is possible upload Feature-Extraction.py with capability of generate class (relax,sad,angry...)

**Comment by SunnerLi** [comment]
Hi @Ealireza ,
I think the goal of `Feature-Extraction.py` is only extract the feature with librosa.
Thus, it doesn't provide the label of emotion automatically.
Maybe you can write the script to add the emotion manually.

**Comment by OmarOsaleh** [comment]
If you write it can you send it or is there a way to know the emotions from the features only?

**Comment by danyalimran93** [comment]
Yup, the goal of the `Feature-Extraction.py` is to extract the features and not label the emotions, because if a computer is going to label the emotions and then classify them later on, what's the point without any human intervention?
